[2023-11-26T12:10:04.183+0000] {processor.py:157} INFO - Started process (PID=172) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:10:04.188+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:10:04.193+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:10:04.191+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:10:04.421+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:10:04.402+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:10:04.424+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:10:04.474+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.305 seconds
[2023-11-26T12:10:34.903+0000] {processor.py:157} INFO - Started process (PID=189) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:10:34.905+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:10:34.907+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:10:34.907+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:10:34.983+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:10:34.979+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:10:34.984+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:10:35.020+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.121 seconds
[2023-11-26T12:11:05.291+0000] {processor.py:157} INFO - Started process (PID=206) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:11:05.293+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:11:05.295+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:11:05.295+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:11:05.385+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:11:05.374+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:11:05.386+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:11:05.449+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.163 seconds
[2023-11-26T12:11:35.770+0000] {processor.py:157} INFO - Started process (PID=223) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:11:35.772+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:11:35.775+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:11:35.774+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:11:35.864+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:11:35.852+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:11:35.866+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:11:35.884+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.120 seconds
[2023-11-26T12:12:06.255+0000] {processor.py:157} INFO - Started process (PID=240) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:12:06.256+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:12:06.258+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:12:06.258+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:12:06.337+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:12:06.327+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:12:06.339+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:12:06.361+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.113 seconds
[2023-11-26T12:12:36.665+0000] {processor.py:157} INFO - Started process (PID=257) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:12:36.668+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:12:36.671+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:12:36.670+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:12:36.766+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:12:36.755+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:12:36.767+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:12:36.787+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.131 seconds
[2023-11-26T12:13:07.137+0000] {processor.py:157} INFO - Started process (PID=274) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:13:07.140+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:13:07.142+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:13:07.142+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:13:07.228+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:13:07.217+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:13:07.230+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:13:07.250+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.120 seconds
[2023-11-26T12:13:37.551+0000] {processor.py:157} INFO - Started process (PID=291) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:13:37.554+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:13:37.557+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:13:37.557+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:13:37.644+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:13:37.635+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:13:37.646+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:13:37.665+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.119 seconds
[2023-11-26T12:14:08.021+0000] {processor.py:157} INFO - Started process (PID=308) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:14:08.023+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:14:08.025+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:14:08.024+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:14:08.121+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:14:08.112+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:14:08.123+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:14:08.207+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.192 seconds
[2023-11-26T12:14:38.661+0000] {processor.py:157} INFO - Started process (PID=325) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:14:38.742+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:14:38.745+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:14:38.744+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:14:38.890+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:14:38.883+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:14:38.891+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:14:38.981+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.329 seconds
[2023-11-26T12:15:09.935+0000] {processor.py:157} INFO - Started process (PID=342) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:15:09.938+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:15:09.940+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:15:09.939+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:15:10.017+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:15:10.008+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:15:10.018+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:15:10.038+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.114 seconds
[2023-11-26T12:15:41.023+0000] {processor.py:157} INFO - Started process (PID=359) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:15:41.025+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:15:41.026+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:15:41.026+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:15:41.089+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:15:41.083+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:15:41.090+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:15:41.110+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.094 seconds
[2023-11-26T12:16:11.622+0000] {processor.py:157} INFO - Started process (PID=376) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:16:11.624+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:16:11.646+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:16:11.645+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:16:11.843+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:16:11.829+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:16:11.846+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:16:11.884+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.267 seconds
[2023-11-26T12:16:42.349+0000] {processor.py:157} INFO - Started process (PID=393) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:16:42.354+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:16:42.360+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:16:42.358+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:16:42.591+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:16:42.570+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:16:42.594+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:16:42.652+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.324 seconds
[2023-11-26T12:17:13.187+0000] {processor.py:157} INFO - Started process (PID=410) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:17:13.189+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:17:13.191+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:17:13.191+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:17:13.257+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:17:13.248+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:17:13.258+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:17:13.320+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.138 seconds
[2023-11-26T12:17:43.606+0000] {processor.py:157} INFO - Started process (PID=427) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:17:43.608+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:17:43.610+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:17:43.609+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:17:43.676+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:17:43.670+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:17:43.677+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:17:43.738+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.138 seconds
[2023-11-26T12:18:14.119+0000] {processor.py:157} INFO - Started process (PID=444) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:18:14.121+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:18:14.123+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:18:14.123+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:18:14.210+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:18:14.198+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:18:14.211+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:18:14.233+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.121 seconds
[2023-11-26T12:18:44.630+0000] {processor.py:157} INFO - Started process (PID=461) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:18:44.632+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:18:44.634+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:18:44.634+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:18:44.718+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:18:44.706+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:18:44.720+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:18:44.783+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.161 seconds
[2023-11-26T12:19:15.131+0000] {processor.py:157} INFO - Started process (PID=478) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:19:15.133+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:19:15.136+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:19:15.135+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:19:15.225+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:19:15.213+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:19:15.226+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:19:15.292+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.168 seconds
[2023-11-26T12:19:45.699+0000] {processor.py:157} INFO - Started process (PID=495) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:19:45.702+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:19:45.705+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:19:45.704+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:19:45.799+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:19:45.785+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:19:45.800+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:19:45.831+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.140 seconds
[2023-11-26T12:20:16.350+0000] {processor.py:157} INFO - Started process (PID=512) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:20:16.353+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:20:16.355+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:20:16.354+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:20:16.451+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:20:16.438+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('postgre_sql_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_sql_conn` isn't defined
[2023-11-26T12:20:16.453+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:20:16.472+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.127 seconds
[2023-11-26T12:20:20.635+0000] {processor.py:157} INFO - Started process (PID=522) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:20:20.637+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:20:20.638+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:20:20.638+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:20:20.815+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:20:20.804+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('Test_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `Test_conn` isn't defined
[2023-11-26T12:20:20.817+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:20:20.837+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.207 seconds
[2023-11-26T12:20:51.123+0000] {processor.py:157} INFO - Started process (PID=539) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:20:51.127+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:20:51.130+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:20:51.129+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:20:51.216+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:20:51.206+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('Test_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `Test_conn` isn't defined
[2023-11-26T12:20:51.217+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:20:51.278+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.159 seconds
[2023-11-26T12:21:21.778+0000] {processor.py:157} INFO - Started process (PID=556) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:21:21.781+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:21:21.784+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:21:21.783+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:21:21.878+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:21:21.868+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('Test_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `Test_conn` isn't defined
[2023-11-26T12:21:21.880+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:21:21.899+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.127 seconds
[2023-11-26T12:21:52.390+0000] {processor.py:157} INFO - Started process (PID=573) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:21:52.392+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:21:52.394+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:21:52.393+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:21:52.489+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:21:52.476+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 7, in <module>
    postgre_con = BaseHook.get_connection('Test_conn')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `Test_conn` isn't defined
[2023-11-26T12:21:52.492+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:21:52.513+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.128 seconds
[2023-11-26T12:22:22.976+0000] {processor.py:157} INFO - Started process (PID=590) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:22:22.978+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:22:22.979+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:22:22.979+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:22:23.074+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:22:23.074+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:22:23.099+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:22:23.089+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 51, in <module>
    bash_command=f"python3 /opt/airflow/dags/pg_read.py {postgre_con_host} {airflow} {airflow} {postgre_con_port}"
NameError: name 'airflow' is not defined
[2023-11-26T12:22:23.104+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:22:23.125+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.154 seconds
[2023-11-26T12:22:53.633+0000] {processor.py:157} INFO - Started process (PID=607) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:22:53.634+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:22:53.637+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:22:53.636+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:22:53.718+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:22:53.717+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:22:53.744+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:22:53.730+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 51, in <module>
    bash_command=f"python3 /opt/airflow/dags/pg_read.py {postgre_con_host} {airflow} {airflow} {postgre_con_port}"
NameError: name 'airflow' is not defined
[2023-11-26T12:22:53.749+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:22:53.817+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.191 seconds
[2023-11-26T12:23:24.147+0000] {processor.py:157} INFO - Started process (PID=624) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:23:24.150+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:23:24.153+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:23:24.152+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:23:24.235+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:23:24.235+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:23:24.254+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:23:24.246+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 51, in <module>
    bash_command=f"python3 /opt/airflow/dags/pg_read.py {postgre_con_host} {airflow} {airflow} {postgre_con_port}"
NameError: name 'airflow' is not defined
[2023-11-26T12:23:24.257+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:23:24.280+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.141 seconds
[2023-11-26T12:23:54.815+0000] {processor.py:157} INFO - Started process (PID=641) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:23:54.818+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:23:54.822+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:23:54.821+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:23:54.903+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:23:54.903+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:23:54.925+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:23:54.912+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 51, in <module>
    bash_command=f"python3 /opt/airflow/dags/pg_read.py {postgre_con_host} {airflow} {airflow} {postgre_con_port}"
NameError: name 'airflow' is not defined
[2023-11-26T12:23:54.928+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:23:54.989+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.179 seconds
[2023-11-26T12:24:25.515+0000] {processor.py:157} INFO - Started process (PID=658) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:24:25.517+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:24:25.518+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:24:25.518+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:24:25.597+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:24:25.597+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:24:25.617+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:24:25.606+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 51, in <module>
    bash_command=f"python3 /opt/airflow/dags/pg_read.py {postgre_con_host} {airflow} {airflow} {postgre_con_port}"
NameError: name 'airflow' is not defined
[2023-11-26T12:24:25.621+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:24:25.639+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.130 seconds
[2023-11-26T12:24:56.166+0000] {processor.py:157} INFO - Started process (PID=675) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:24:56.168+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:24:56.170+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:24:56.169+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:24:56.239+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:24:56.238+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:24:56.258+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:24:56.247+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 51, in <module>
    bash_command=f"python3 /opt/airflow/dags/pg_read.py {postgre_con_host} {airflow} {airflow} {postgre_con_port}"
NameError: name 'airflow' is not defined
[2023-11-26T12:24:56.262+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:24:56.321+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.160 seconds
[2023-11-26T12:25:27.018+0000] {processor.py:157} INFO - Started process (PID=694) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:25:27.020+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:25:27.023+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:25:27.022+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:25:27.082+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:25:27.082+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:25:27.098+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:25:27.090+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 51, in <module>
    bash_command=f"python3 /opt/airflow/dags/pg_read.py {postgre_con_host} {airflow} {airflow} {postgre_con_port}"
NameError: name 'airflow' is not defined
[2023-11-26T12:25:27.102+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:25:27.118+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.104 seconds
[2023-11-26T12:25:57.659+0000] {processor.py:157} INFO - Started process (PID=716) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:25:57.661+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:25:57.663+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:25:57.662+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:25:57.742+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:25:57.742+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:25:57.764+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:25:57.750+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 51, in <module>
    bash_command=f"python3 /opt/airflow/dags/pg_read.py {postgre_con_host} {airflow} {airflow} {postgre_con_port}"
NameError: name 'airflow' is not defined
[2023-11-26T12:25:57.768+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:25:57.789+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.136 seconds
[2023-11-26T12:26:28.310+0000] {processor.py:157} INFO - Started process (PID=733) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:26:28.312+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:26:28.314+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:26:28.313+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:26:28.403+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:26:28.402+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:26:28.422+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:26:28.410+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 51, in <module>
    bash_command=f"python3 /opt/airflow/dags/pg_read.py {postgre_con_host} {airflow} {airflow} {postgre_con_port}"
NameError: name 'airflow' is not defined
[2023-11-26T12:26:28.428+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:26:28.490+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.184 seconds
[2023-11-26T12:26:59.004+0000] {processor.py:157} INFO - Started process (PID=750) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:26:59.006+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:26:59.008+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:26:59.007+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:26:59.102+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:26:59.101+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:26:59.122+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:26:59.111+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 51, in <module>
    bash_command=f"python3 /opt/airflow/dags/pg_read.py {postgre_con_host} {airflow} {airflow} {postgre_con_port}"
NameError: name 'airflow' is not defined
[2023-11-26T12:26:59.127+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:26:59.174+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.176 seconds
[2023-11-26T12:27:29.493+0000] {processor.py:157} INFO - Started process (PID=767) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:27:29.495+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:27:29.497+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:27:29.496+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:27:29.579+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:27:29.579+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:27:29.601+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:27:29.589+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 51, in <module>
    bash_command=f"python3 /opt/airflow/dags/pg_read.py {postgre_con_host} {airflow} {airflow} {postgre_con_port}"
NameError: name 'airflow' is not defined
[2023-11-26T12:27:29.604+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:27:29.667+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.179 seconds
[2023-11-26T12:28:00.187+0000] {processor.py:157} INFO - Started process (PID=784) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:28:00.190+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:28:00.192+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:28:00.191+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:28:00.280+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:28:00.279+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:28:00.300+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:28:00.289+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 51, in <module>
    bash_command=f"python3 /opt/airflow/dags/pg_read.py {postgre_con_host} {airflow} {airflow} {postgre_con_port}"
NameError: name 'airflow' is not defined
[2023-11-26T12:28:00.304+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:28:00.368+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.185 seconds
[2023-11-26T12:28:30.898+0000] {processor.py:157} INFO - Started process (PID=801) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:28:30.901+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:28:30.902+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:28:30.902+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:28:30.987+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:28:30.987+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:28:31.007+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:28:30.996+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 51, in <module>
    bash_command=f"python3 /opt/airflow/dags/pg_read.py {postgre_con_host} {airflow} {airflow} {postgre_con_port}"
NameError: name 'airflow' is not defined
[2023-11-26T12:28:31.011+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:28:31.031+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.139 seconds
[2023-11-26T12:29:01.480+0000] {processor.py:157} INFO - Started process (PID=818) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:29:01.482+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:29:01.485+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:29:01.485+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:29:01.565+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:29:01.565+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:29:01.583+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:29:01.572+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/pg_read_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/pg_read_dag.py", line 51, in <module>
    bash_command=f"python3 /opt/airflow/dags/pg_read.py {postgre_con_host} {airflow} {airflow} {postgre_con_port}"
NameError: name 'airflow' is not defined
[2023-11-26T12:29:01.589+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:29:01.607+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.132 seconds
[2023-11-26T12:29:08.805+0000] {processor.py:157} INFO - Started process (PID=828) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:29:08.807+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:29:08.810+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:29:08.809+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:29:08.920+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:29:08.919+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:29:08.942+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:29:09.280+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:29:09.279+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-26T12:29:09.316+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:29:09.315+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-26T12:29:09.340+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:29:09.340+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-26T12:29:09.342+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:29:09.341+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:29:09.380+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:29:09.380+0000] {dag.py:2963} INFO - Creating ORM DAG for dag_pg_read
[2023-11-26T12:29:09.427+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:29:09.426+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:29:09.501+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.703 seconds
[2023-11-26T12:29:40.263+0000] {processor.py:157} INFO - Started process (PID=846) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:29:40.265+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:29:40.268+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:29:40.267+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:29:40.345+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:29:40.345+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:29:40.356+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:29:40.373+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:29:40.372+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:29:40.462+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:29:40.462+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:29:40.503+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.245 seconds
[2023-11-26T12:30:10.978+0000] {processor.py:157} INFO - Started process (PID=866) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:30:10.981+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:30:10.984+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:30:10.983+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:30:11.086+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:30:11.085+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:30:11.099+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:30:11.128+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:30:11.127+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:30:11.163+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:30:11.162+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:30:11.245+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.275 seconds
[2023-11-26T12:30:41.868+0000] {processor.py:157} INFO - Started process (PID=885) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:30:41.870+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:30:41.871+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:30:41.871+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:30:41.926+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:30:41.926+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:30:41.940+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:30:41.962+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:30:41.962+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:30:41.987+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:30:41.987+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:30:42.073+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.209 seconds
[2023-11-26T12:31:12.494+0000] {processor.py:157} INFO - Started process (PID=902) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:31:12.496+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:31:12.497+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:31:12.497+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:31:12.555+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:31:12.555+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:31:12.566+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:31:12.584+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:31:12.584+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:31:12.616+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:31:12.616+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:31:12.653+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.162 seconds
[2023-11-26T12:31:43.033+0000] {processor.py:157} INFO - Started process (PID=983) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:31:43.035+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:31:43.037+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:31:43.036+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:31:43.089+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:31:43.089+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:31:43.098+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:31:43.119+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:31:43.119+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:31:43.157+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:31:43.157+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:31:43.194+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.165 seconds
[2023-11-26T12:32:13.615+0000] {processor.py:157} INFO - Started process (PID=1000) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:32:13.617+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:32:13.618+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:32:13.618+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:32:13.654+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:32:13.654+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:32:13.663+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:32:13.679+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:32:13.678+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:32:13.710+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:32:13.710+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:32:13.740+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.129 seconds
[2023-11-26T12:32:44.135+0000] {processor.py:157} INFO - Started process (PID=1017) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:32:44.137+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:32:44.138+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:32:44.138+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:32:44.178+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:32:44.177+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:32:44.188+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:32:44.208+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:32:44.208+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:32:44.244+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:32:44.244+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:32:44.277+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.146 seconds
[2023-11-26T12:33:14.660+0000] {processor.py:157} INFO - Started process (PID=1034) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:33:14.662+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:33:14.664+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:33:14.664+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:33:14.721+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:33:14.721+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:33:14.732+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:33:14.748+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:33:14.748+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:33:14.773+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:33:14.773+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:33:14.802+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.148 seconds
[2023-11-26T12:33:45.199+0000] {processor.py:157} INFO - Started process (PID=1051) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:33:45.201+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:33:45.203+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:33:45.202+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:33:45.266+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:33:45.265+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:33:45.274+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:33:45.293+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:33:45.293+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:33:45.323+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:33:45.323+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:33:45.402+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.208 seconds
[2023-11-26T12:34:15.856+0000] {processor.py:157} INFO - Started process (PID=1068) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:34:15.859+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:34:15.861+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:34:15.861+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:34:15.932+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:34:15.932+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:34:15.944+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:34:15.963+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:34:15.963+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:34:15.984+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:34:15.984+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:34:16.071+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.223 seconds
[2023-11-26T12:34:46.499+0000] {processor.py:157} INFO - Started process (PID=1117) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:34:46.501+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:34:46.502+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:34:46.502+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:34:46.562+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:34:46.562+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:34:46.574+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:34:46.591+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:34:46.591+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:34:46.619+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:34:46.618+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:34:46.694+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.199 seconds
[2023-11-26T12:35:17.129+0000] {processor.py:157} INFO - Started process (PID=1134) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:35:17.131+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:35:17.132+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:35:17.132+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:35:17.191+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:35:17.190+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:35:17.202+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:35:17.224+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:35:17.223+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:35:17.261+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:35:17.260+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:35:17.340+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.214 seconds
[2023-11-26T12:35:47.820+0000] {processor.py:157} INFO - Started process (PID=1151) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:35:47.822+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:35:47.823+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:35:47.823+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:35:47.888+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:35:47.887+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:35:47.901+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:35:47.919+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:35:47.919+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:35:47.959+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:35:47.959+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:35:48.052+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.236 seconds
[2023-11-26T12:36:18.519+0000] {processor.py:157} INFO - Started process (PID=1168) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:36:18.521+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:36:18.523+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:36:18.522+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:36:18.577+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:36:18.577+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:36:18.590+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:36:18.612+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:36:18.611+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:36:18.642+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:36:18.642+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:36:18.672+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.158 seconds
[2023-11-26T12:36:49.137+0000] {processor.py:157} INFO - Started process (PID=1185) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:36:49.138+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:36:49.140+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:36:49.140+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:36:49.208+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:36:49.207+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:36:49.221+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:36:49.238+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:36:49.237+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:36:49.262+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:36:49.262+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:36:49.344+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.213 seconds
[2023-11-26T12:37:19.833+0000] {processor.py:157} INFO - Started process (PID=1202) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:37:19.835+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:37:19.837+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:37:19.837+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:37:19.904+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:37:19.904+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:37:19.918+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:37:19.937+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:37:19.936+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:37:19.969+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:37:19.969+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:37:20.003+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.179 seconds
[2023-11-26T12:37:50.387+0000] {processor.py:157} INFO - Started process (PID=1219) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:37:50.389+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:37:50.391+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:37:50.391+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:37:50.463+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:37:50.463+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:37:50.478+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:37:50.637+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:37:50.637+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:37:50.674+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:37:50.673+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:37:50.717+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.338 seconds
[2023-11-26T12:38:21.179+0000] {processor.py:157} INFO - Started process (PID=1268) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:38:21.181+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:38:21.183+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:38:21.183+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:38:21.240+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:38:21.240+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:38:21.250+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:38:21.264+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:38:21.264+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:38:21.289+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:38:21.289+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:38:21.361+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.186 seconds
[2023-11-26T12:38:51.797+0000] {processor.py:157} INFO - Started process (PID=1285) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:38:51.798+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:38:51.800+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:38:51.800+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:38:51.858+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:38:51.858+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:38:51.868+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:38:51.883+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:38:51.883+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:38:51.911+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:38:51.911+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:38:51.938+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.148 seconds
[2023-11-26T12:39:22.411+0000] {processor.py:157} INFO - Started process (PID=1302) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:39:22.414+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:39:22.418+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:39:22.417+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:39:22.510+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:39:22.509+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:39:22.524+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:39:22.542+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:39:22.542+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:39:22.575+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:39:22.575+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:39:22.612+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.211 seconds
[2023-11-26T12:39:53.052+0000] {processor.py:157} INFO - Started process (PID=1319) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:39:53.054+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:39:53.055+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:39:53.055+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:39:53.106+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:39:53.106+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:39:53.122+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:39:53.146+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:39:53.145+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:39:53.175+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:39:53.175+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:39:53.254+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.206 seconds
[2023-11-26T12:40:23.644+0000] {processor.py:157} INFO - Started process (PID=1336) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:40:23.646+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:40:23.647+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:40:23.647+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:40:23.697+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:40:23.697+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:40:23.706+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:40:23.722+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:40:23.721+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:40:23.758+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:40:23.758+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:40:23.837+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.196 seconds
[2023-11-26T12:40:54.235+0000] {processor.py:157} INFO - Started process (PID=1353) to work on /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:40:54.237+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/pg_read_dag.py for tasks to queue
[2023-11-26T12:40:54.238+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:40:54.238+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:40:54.292+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:40:54.292+0000] {base.py:73} INFO - Using connection ID 'Test_conn' for task execution.
[2023-11-26T12:40:54.300+0000] {processor.py:839} INFO - DAG(s) dict_keys(['dag_pg_read']) retrieved from /opt/airflow/dags/pg_read_dag.py
[2023-11-26T12:40:54.313+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:40:54.313+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-26T12:40:54.339+0000] {logging_mixin.py:151} INFO - [2023-11-26T12:40:54.339+0000] {dag.py:3722} INFO - Setting next_dagrun for dag_pg_read to 2023-11-24T18:00:00+00:00, run_after=2023-11-25T18:00:00+00:00
[2023-11-26T12:40:54.362+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/pg_read_dag.py took 0.132 seconds
